### ISSUE TITLE
Adding festival-based intents

### ISSUE THREAD

**Issue by StrixzIV** [Celestial-Project/Celestial-Legacy#15]
I'm tryin to make an festival-based chat intents that check how close to the festival is and responds corresponds to the festival.

**Comment by doclai** [comment]
Could you give more information on "festival-based chat intents"?

**Comment by StrixzIV** [comment]
It's like 

fes_date = 31/12/2022

if date == festival_date:
    return "Festival"
    
else:
    return "Not this festival yet"
    
 but you change the return part with you custom responses

**Comment by StrixzIV** [comment]
I don't know if this is enough for the festival's intent handling 
but I add the condition response that will check if the current date is the same as the festival date.

If the date is the same: return a response that said "Today is *x* festival".
If not: return a response that said "Today is not *x* festival"
