### ISSUE TITLE
"-r" or "reload" bug

### ISSUE THREAD

**Issue by Peachpiggies** [Celestial-Project/Celestial-Legacy#5]
<img width="960" alt="Screenshot 2022-07-01 215054" src="https://user-images.githubusercontent.com/97142113/176918467-36450323-02bb-41bb-ae85-e2c9437c1e02.png">

**Comment by StrixzIV** [comment]
I've already make a fix commit [here](https://github.com/StrixzIV/Celestial/pull/6/commits/560034df6a45b72ad418d309c3db77f814cda248).
is that thing working now?

**Comment by Peachpiggies** [comment]
It's working now bro. **VERY COOL**.

**Comment by StrixzIV** [comment]
Ok, I'll close this issue.
