### ISSUE TITLE
"-r" or "reload" is bugged again

### ISSUE THREAD

**Issue by Peachpiggies** [Celestial-Project/Celestial-Legacy#8]
When it's reloaded it is straight at the start of the column
<img width="960" alt="image" src="https://user-images.githubusercontent.com/97142113/176984734-d00e34b3-394a-4e22-8324-316d524f3249.png">
@StrixzIV 

- [Pls fix this]

**Comment by StrixzIV** [comment]
OK, I've fixed the bug [here](https://github.com/StrixzIV/Celestial/blob/fix-reload-bug2/cli_tester.py) can u change the file and test if it working now?

I change the reload behavior to just reload only the chat_responses module which read the JSON file when called but not a whole program which removes the delay when the program reloads too.

**Comment by StrixzIV** [comment]
Pls make a review [here](https://github.com/StrixzIV/Celestial/pull/9) pls.
